### ISSUE TITLE
BufferedReader used for ContextualPatch 

### ISSUE THREAD

**Issue by shahharsh** [cloudbees/diff4j#4]
The ContextualPatch is having problem if the patch files and script are on different platforms. BufferedReader readline will create problems while reading files from linux and windows system.

here is the problem where it is breaking.
https://issues.jenkins-ci.org/browse/JENKINS-27169

Regards
H Shah

**Comment by kohsuke** [comment]
I've addressed this a little differently in my fixup to pull request #5 

When diff4j reads files to patch, it does so with the platform default encoding. I think the patch file should be read in the same way.
